services:
  - type: web
    name: uzicare-forecasting-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r final_model/requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT forecasting_api:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
